import { PrismaClient, Prisma } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';

/**
 * OPS-003: Tenant Re-import Tool
 * Recovers a specific tenant from a JSON dump (generated by export-tenant.ts).
 */
async function importTenantData(filePath: string, targetTenantId: string) {
    const prisma = new PrismaClient();

    if (!fs.existsSync(filePath)) {
        console.error(`ERROR: File not found at ${filePath}`);
        process.exit(1);
    }

    console.log(`Loading export file: ${filePath}`);
    const rawData = fs.readFileSync(filePath, 'utf8');
    const exportData = JSON.parse(rawData);

    console.log(`Starting import for Target Tenant ID: ${targetTenantId}...`);

    // In a real disaster recovery scenario, you'd want to handle relationships.
    // The safest approach for raw data recovery is to disable FK checks temporarily
    // within a transaction, insert everything, and commit.
    // However, Prisma doesn't support session-level constraint disabling across multiple executeRaw calls
    // easily without raw SQL.

    // Ordered insertion based on core dependencies
    const insertionOrder = [
        'TenantUser', 'Account', 'Product', 'Supplier', 'Customer', 'Department', 'Employee',
        'JournalEntry', 'Transaction', 'Invoice', 'InvoiceItem', 'PurchaseOrder', 'PurchaseOrderItem',
        'Payment', 'CreditNote', 'DebitNote', 'AuditLog', 'IdempotencyKey', 'GovernanceProfile'
    ];

    // Build ordered list of models that exist in the export
    const availableModels = Object.keys(exportData);
    const orderedModels = insertionOrder.filter(m => availableModels.includes(m));
    const remainingModels = availableModels.filter(m => !insertionOrder.includes(m));
    const fullOrder = [...orderedModels, ...remainingModels];

    try {
        await prisma.$transaction(async (tx) => {
            // Optional: Clean existing data for this tenant to prevent unique constraint errors
            console.warn(`NOTE: This script attempts to upsert or insert raw data.`);

            for (const modelName of fullOrder) {
                const lowerModelName = modelName.charAt(0).toLowerCase() + modelName.slice(1);
                const records = exportData[modelName];

                if (!records || records.length === 0) continue;

                console.log(`Importing ${records.length} records into [${modelName}]...`);

                let successCount = 0;
                let failCount = 0;

                for (const record of records) {
                    try {
                        // Ensure the record belongs to the target tenant if we are cloning
                        if (record.tenantId) {
                            record.tenantId = targetTenantId;
                        }

                        // We use direct create or upsert depending on the data model. 
                        // For generic re-import, we attempt to create. If it exists, we skip.
                        // Production DR tools would use robust UPSERT logic per model.
                        await (tx as any)[lowerModelName].create({
                            data: { ...record },
                        });
                        successCount++;
                    } catch (e: any) {
                        // Ignore unique constraint violations (P2002) if we're doing a partial recovery
                        if (e.code === 'P2002') {
                            // Record already exists, skip.
                            failCount++;
                        } else {
                            console.error(`Failed to insert record into ${modelName}:`, e.message);
                            throw e; // Rollback the whole transaction on structural failure
                        }
                    }
                }
                console.log(`  -> Inserted: ${successCount}. Skipped (existing): ${failCount}.`);
            }
        }, {
            timeout: 60000, // 1 minute timeout for large imports
            isolationLevel: 'Serializable'
        });

        console.log(`\nImport complete! Data successfully restored/merged for ${targetTenantId}.`);
    } catch (e) {
        console.error(`\n[CRITICAL ERROR] Import reverted due to failure:`, e);
    } finally {
        await prisma.$disconnect();
    }
}

const file = process.argv[2];
const tid = process.argv[3];
if (!file || !tid) {
    console.error('Usage: ts-node scripts/import-tenant.ts <PATH_TO_JSON_FILE> <TARGET_TENANT_ID>');
    process.exit(1);
}

importTenantData(file, tid).catch(err => {
    console.error('Fatal execution error:', err);
    process.exit(1);
});
